name: Pull Request

on: pull_request

jobs:
  check:
    timeout-minutes: 5
    strategy:
      matrix:
        os: [
            ubuntu-latest,
            # windows-latest,
            # macos-latest,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: oven-sh/setup-bun@v1

      - run: npm install -f
      - run: bun run build
      - run: bun run check
